### ISSUE TITLE
Trait not found

### ISSUE THREAD

**Issue by joecharm** [ycore/fortify-tailwind#1]
Fresh Laravel application installed with only Fortify. Following the steps to install the package however then registering a user results in this error:

`Trait 'Ycore\FortifyUi\Actions\PasswordValidationRules' not found`

**Comment by jj-meyer** [comment]
Thanks @joecharm for the heads-up. I pushed v1.2.2 to address the issue. 
Also updated the readme to include installing `autoprefixer` with `tailwindcss` for compatibility with @latest `tailwindcss` 

Update to v1.2.2 and re-publish the assets on that existing install if you wish.

```bash
composer update ycore/fortify-tailwind
php artisan fortify-ui:tailwind --force
```
